config/routes.rb
Fruithome::Application.routes.draw do
  root 'fruit#index'
	get "about" => "about#index"
	
	get "login" => "user#login"
	post "login" => "user#login"
	post "register" => "user#register"
	get "register" => "user#register"
	get "user" => "user#index"
	get "logout" => "user#logout"
	get "user/information"
	get "user/security"
	get "user/change_password"
	post "user/change_password"
	get "user/update_mail_address"
	post "user/update_mail_address"
	get "user/edit_info" 
	get "user/edit_security" 
	post "user/update_info"
	post "user/update_security"
	
	
  get "index" => "fruit#index"
  get "search" => "fruit#search"
	get "show" => "fruit#show"
	post "add_to_cart" => "fruit#add_to_cart"
  post "fruit/collect"
	
  get "order/index" => "order#index"
  get "order/show" => "order#show"
  get "order/destroy"
  post "order/order_done"
	get "order/pay" => "order#pay"
	get "order/collection" => "order#collection"
	get "order/pay_success"
	get "order/collection"
	post "order/cancel_collection"
	
	get "cart/show" => "cart#show"
  post "cart/destroy"
	
  get "admin/fruit_type/new" => "admin/fruit_type#new"
  post "admin/fruit_type/create" => "admin/fruit_type#create"
  get "admin/fruit_type/edit"
  post "admin/fruit_type/update"
  post "admin/fruit_type/destroy"
  get "admin/fruit_type/show"
  get "admin/fruit_type" => "admin/fruit_type#index"
	
  get "admin/origin_place/new" => "admin/origin_place#new"
  post "admin/origin_place/create" => "admin/origin_place#create"
  get "admin/origin_place/edit"
  post "admin/origin_place/update"
  post "admin/origin_place/destroy"
  get "admin/origin_place/show"
  get "admin/origin_place" => "admin/origin_place#index"
	
  get "admin/fruit/new" => "admin/fruit#new"
  post "admin/fruit/create" => "admin/fruit#create"
  get "admin/fruit/edit"
  post "admin/fruit/update"
  post "admin/fruit/destroy"
  get "admin/fruit/show"
  get "admin/fruit" => "admin/fruit#index"
	
	get "admin/order/new" => "admin/order#new"
  post "admin/order/create" => "admin/order#create"
  get "admin/order/edit"
  post "admin/order/update"
  post "admin/order/destroy"
  get "admin/order/show"
  get "admin/order/history"
  get "admin/order" => "admin/order#index"
	
	get "admin/login" => "admin/user#login"
	post "admin/login" => "admin/user#login"
	get "admin/logout" => "admin/user#logout"
	get "admin/user/index"
	get "admin/user/information"
	get "admin/user/edit_info"
	post "admin/user/update_info"
	get "admin/user/security"
	get "admin/user/change_password"
	post "admin/user/change_password"
	post "admin/user/update_mail_address"
	get "admin/user/edit_security" 
	post "admin/user/update_security"
	
  get "admin/member/new" => "admin/member#new"
  post "admin/member/create" => "admin/member#create"
  get "admin/member" => "admin/member#index"
  get "admin/member/banned"
  get "admin/member/edit"
  post "admin/member/update"
  post "admin/member/destroy"
  get "admin/member/show"
	
  
  

end

app/models/order.rb
# -*- encoding: utf-8 -*-
class Order < ActiveRecord::Base

	belongs_to :user
	has_many :order_items
	has_many :fruits, :through => :order_items
	
	# TruitName_MIN_LENGTH = 1
	# TruitName_MAX_LENGTH = 20
	# TruitName_RANGE = TruitName_MIN_LENGTH..TruitName_MAX_LENGTH
	# Description_MIN_LENGTH = 12
	# Description_MAX_LENGTH = 200
	# Description_RANGE = Description_MIN_LENGTH..Description_MAX_LENGTH
	
	# validates :fruit_id,	:presence => true												
	# validates :user_id,		:presence => true
	# validates :fruit_amount,	
												# :presence => true

	def	status_text
																					#0:已确认,购物车状态;
																					#1:已付款，等待发货;
																					#2:已发货，等待验收;
																					#3:已签收，交易完成，等待评价;
																					#4:已评价，订单完成将关闭；
																					#9:已完成，正常完成状态
																					#10:已取消交易
																					#11:退货等;
		t = case	self.status
					when 1	then	"已确认"
					when 2	then	"已发货"
					when 3	then	"已签收"
					when 4..9	then	"已完成"
					when 10 	then	"已取消"
					when 11		then	"退货"
				end
	end

end

app/controllers/admin/order_controller.rb
# -*- encoding: utf-8 -*-
class Admin::OrderController < ApplicationController
layout "admin_layout"
include ApplicationHelper
before_filter :admin_login_required
  def new
		@order = Order.new
		@page_title = "订单管理"
  end

  def create
		if request.post? and params[:order]
			@order = Order.new(order_params)
			if @order.save
				flash[:notice] = order_params[:user_id].to_s #"添加成功"
				redirect_to :action => "show", :id => @order.id
			else
				flash[:alert] = errors_for(@order, "抱歉，请检查输入信息：").html_safe
				render :action => "new"
			end
		end
  end

  def edit
		@order = Order.find(params[:id])
		@order_items = @order.order_items
		@page_title = @order.id
  end

  def update
		if request.post? and params[:order]
			@order = Order.find(params[:id])
			
			
			if @order.update_attributes(order_params) and @order.order_items.each {|item| item.update_attributes(price:params[item.id.to_s][:price],quantity:params[item.id.to_s][:quantity])}
				flash[:notice] = order_params[:user_id].to_s #"更新成功"
				redirect_to :action => "show", :id => @order.id
			else
				flash[:alert] = errors_for(@order, "抱歉，请检查输入信息：").html_safe
				render :action => "edit"
			end
		end
  end

  def destroy
		if request.post? and params[:id]
			@order = Order.find(params[:id])
			@order.status = 9
			if @order.save
				flash[:notice] = "成功取消订单#{@order.id}" #"取消成功"
			end
			# flash[:alert] = errors_for(@order, "抱歉，请检查输入信息：").html_safe
			redirect_to :action => "index"
		end
  end

  def show
		@order = Order.find(params[:id])
		@page_title = @order.user_id
  end

  def index
		@orders = Order.where.not(status:[nil,0,9],user_id:[nil,0])
		@page_title = "订单"
  end

  def history
		@orders = Order.where(status:[9]).where.not(user_id:[nil,0])
		@page_title = "订单"
  end

	private
	def order_params
		params.require(:order).permit(:user_id,
																	:consignee_name,
																	:consignee_address,
																	:consignee_phone,
																	:remark,
																	:total_price,
																	:status)
	end
end

app/controllers/order_controller.rb
# -*- encoding: utf-8 -*-
class OrderController < ApplicationController
	before_filter :login_required

	
	layout "self_center"
  def index
		@orders = Order.where("user_id =? and status != 0", current_user.id)
  end
	
	def show
		@order = Order.find(params[:id])
	end
	def cart
		 # @fruit = Order.first
	end
	def destroy
		 if Order.find(params[:id]).update(status:"10")
			redirect_to action:"index"
		 end
	end
	def order_done
		 if Order.find(params[:id]).update(status:"9")
			redirect_to action:"index"
		 end
	end
	def pay
		@page_title = "确认订单"
		@order_items = @cart.order_items
		# @fruit = Fruit.first
		render :layout => "payment_layout"
	end
	def pay_success
		@page_title = "提交订单"
		@order_items = @cart.order_items
		@cart.status = 1
		@cart.consignee_name = @current_user.username
		@cart.consignee_address = @current_user.mail_addresses.first.address
		@cart.consignee_phone = @current_user.phone_number
		sum = 0
		@order_items.each do |ci|
			ci.fruit.inventory -= ci.quantity
			ci.price = ci.fruit.price_present
			sum = ci.fruit.price_present * ci.quantity
			ci.save
		end
		@cart.total_price = sum + 10
		@cart.save
		render action:"pay_success", :layout => "payment_layout"
	end
	def collection
	@collections = Collection.where(user_id:@current_user.id)
	end
	def cancel_collection
		if request.post? and params[:id]
			@item = Collection.find_by_fruit_id(params[:id])
			flash[:notice] = "成功删除：#{@item.fruit.name}" #"删除成功"
			@item.destroy
			# flash[:alert] = errors_for(@fruit, "抱歉，请检查输入信息：").html_safe
			redirect_to :action => "collection"
		end
	end
end

app/views/order/_collection_item.html.erb
<style type="text/css">
.button_to{
	float:left;
}
</style>

<% fruit = collection_item.fruit %>
<% price_p = fruit.price_present.to_f %>
<% price_h = fruit.price_history.to_f %>
<tr>
	<!-- <td>
		<label class="checkbox-inline">
			<input type="checkbox" id="inlineCheckbox1" value="1">
		</label>
	</td> -->
	<td>
		<%= link_to controller:"fruit", :action => "show", :id => fruit do %>
			<%= image_tag "fruit_images/#{get_images(fruit.id).first}", width:"50px", height:"50px", alt:"#{fruit.name}", title:fruit.name %>
			<strong><%= fruit.name %></strong>
		<% end %>
	</td>
	<td><%= fruit.unit %></td>
	<td><%= price_p %></td>
	<td><!-- <%= price_h > price_p ? price_h - price_p : "" %> --></td>
	<td>
		<% if fruit.inventory.to_i > 10 %>
			<span class="label label-success">货源充足</span>
		<% elsif fruit.inventory.to_i >0 %>
			<span class="label label-warning">货源紧张</span>
		<% else %>
			<span class="label">货源暂无</span>
		<% end %>
	</td>
	<td>
		<%= button_to "删除", { :action=> "cancel_collection", :controller => "order", :id=> fruit },
														:confirm => "是否要取消收藏：#{fruit.name}",
														class:"btn btn-danger" %>
	</td>
</tr>

app/views/order/_order.html.erb
<tr border-bottom-width=0px>
	<td colspan="6">
		<span>订单编号：</span>
		<%= link_to controller:"order", :action => "show", :id => order do %>
			<strong><%= order.id %></strong>
		<% end %>
		<%= link_to "查看详情", controller:"order", :action => "show", :id => order %>
		<span style="width:30px"></span>
		<!-- <%= link_to "水果之家", root_path, style:"margin-left:100px;" %> -->
	</td>
</tr>
<tr border-top-width=0px>
	<td>
		<% order.order_items.each do |i| %>
			<%= link_to controller:"fruit", action:"show", id:i.fruit do %>
				<%= image_tag "fruit_images/#{get_images(i.fruit.id).first}", width:"50px", height:"50px", alt:"#{i.fruit.name}", title:i.fruit.name %>
			<% end %>
		<% end %>
	</td>
	<td><%= order.user.username %></td>
	<td><%= order.total_price %></td>
	<td style="text-align:center;"><%= order.created_at.getlocal.to_s[0..19] %></td>
	<td style="text-align:center;">
		<span style="display:block;"><%= order.status_text %></span>
		<%= link_to "查看", controller:"order", :action => "show", :id => order %>
	</td>
	<td style="text-align:center;">
		<% if order.status < 9 %>
			<%= button_to "确认收货", {:action=> "order_done", :id=> order}, :confirm => "请确认已收货！" %>
		<% end %>
		
<script type="text/javascript">
	$(".button_to input").addClass("btn btn-success")
</script>
		<% if order.status < 4 %>
			<%= link_to "取消订单", {action:"destroy", id:order}, confirm:"是否要取消订单？" %>
		<% end %>
	</td>
</tr>

app/views/order/_order_item.html.erb
<style type="text/css">
.button_to{
	float:left;
}
</style>

<% fruit = order_item.fruit %>
<% price_p = fruit.price_present.to_f %>
<% price_h = fruit.price_history.to_f %>
<tr>
	<td>
		<%= link_to controller:"fruit", :action => "show", :id => fruit do %>
			<%= image_tag "fruit_images/#{get_images(fruit.id).first}", width:"50px", height:"50px", alt:"#{fruit.name}", title:fruit.name %>
			<strong><%= fruit.name %></strong>
		<% end %>
	</td>
	<td><%= price_p %></td>
	<td><%= order_item.quantity %></td>
	<td><%= fruit.unit %></td>
	<td><!-- <%= price_h > price_p ? price_h - price_p : "" %> --></td>
	<td>
		<% if fruit.inventory.to_i > 10 %>
			<span class="label label-success">货源充足</span>
		<% elsif fruit.inventory.to_i >0 %>
			<span class="label label-warning">货源紧张</span>
		<% else %>
			<span class="label">货源暂无</span>
		<% end %>
	</td>
</tr>

app/views/order/cart.html.erb
<div class="row-fluid sortable ui-sortable">		
	<div class="box span12" style="">
		<div class="box-header well" data-original-title="">
			我的购物车
		</div>
		<div class="box-content">
			<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
				<table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
					<thead>
						<tr role="row">
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Checkbox: activate to sort column ascending" style="width: 136px;">
								<label class="checkbox-inline">
									<input type="checkbox" id="inlineCheckbox1" value="option1">
								</label>全选
							</th>
							<th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Username: activate to sort column descending" style="width: 136px;">商品</th>
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Date registered: activate to sort column ascending" style="width: 135px;">单价</th>
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Role: activate to sort column ascending" style="width: 48px;">优惠</th>
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending" style="width: 64px;">（地点）库存</th>
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Actions: activate to sort column ascending" style="width: 128px;">数量</th>
							<th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Actions: activate to sort column ascending" style="width: 128px;">Actions</th>
						</tr>
					</thead>   
						
					<tbody role="alert" aria-live="polite" aria-relevant="all">
						<tr class="odd">
							<td class=" sorting_1">
								<label class="checkbox-inline">
									<input type="checkbox" id="inlineCheckbox1" value="option1">
								</label>
							</td>
							<td class=" sorting_1">苹果</td>
							<td class="center ">10</td>
							<td class="center ">优惠</td>
							<td class="center ">
								<span class="label label-important">无货</span>
							</td>
							<td class="center ">数量</td>
							<td class="center ">
								<a class="btn btn-success" href="#">
									收藏                                            
								</a>
								<a class="btn btn-danger" href="#">
									删除
								</a>
							</td>
						</tr>
						<tr class="even">
							<td class=" sorting_1">
								<label class="checkbox-inline">
									<input type="checkbox" id="inlineCheckbox1" value="option1">
								</label>
							</td>
							<td class=" sorting_1">Abraham</td>
							<td class="center ">2012/03/01</td>
							<td class="center ">Member</td>
							<td class="center ">
								<span class="label label-warning">Pending</span>
							</td>
							<td class="center ">数量</td>
							<td class="center ">
								<a class="btn btn-success" href="#">
									收藏                                            
								</a>
								<a class="btn btn-danger" href="#">
									删除
								</a>
							</td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="6">
								2件商品 总价：120元
												优惠：10元
												总计：10元
							</td>
						</tr>
					</tfoot>
				</table>
				<button id="button" class="btn btn-default" >继续购物</button>
				<button id="button" class="btn btn-default" >去结算</button>
			<!-- 	<div class="row-fluid">
					<div class="span12">
						<div class="dataTables_info" id="DataTables_Table_0_info">Showing 1 to 10 of 32 entries</div>
					</div>
					<div class="span12 center">
						<div class="dataTables_paginate paging_bootstrap pagination">
							<ul>
								<li class="prev disabled"><a href="#">← Previous</a></li>
								<li class="active"><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li class="next"><a href="#">Next → </a></li>
							</ul>
						</div>
					</div>
				</div> -->
			</div>            
		</div>
	</div><!--/span-->
</div>

app/views/order/collection.html.erb
<div style="width:1200px;margin:10px auto;">
	<div style="font-size:30px;padding-top:7px;border-bottom:1px solid #999999;">我的收藏</div>
	<div>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<thead>
				<tr role="row">
					<!-- <th style="width: 136px;">
						<label class="checkbox-inline">
							<input type="checkbox" id="inlineCheckbox1" value="all">
						</label>全选
					</th> -->
					<th style="width: 136px;">商品</th>
					<th style="width: 135px;">规格</th>
					<th style="width: 135px;">单价</th>
					<th style="width: 48px;">优惠</th>
					<th style="width: 64px;">库存</th>
					<th style="width: 128px;">Actions</th>
				</tr>
			</thead>   
				
			<tbody role="alert" aria-live="polite" aria-relevant="all">
				<%= render :partial=> "collection_item", :collection => @collections %>
			</tbody>
		</table>
		<div style="text-align:center;">
			<!-- <%= link_to "继续购物", root_path, :class => "btn" %> -->
		</div>
	</div>
</div>

app/views/order/index.html.erb
<div>
	<div>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<thead>
				<tr role="row">
					<th style="width: 136px;">订单信息</th>
					<th style="width: 135px;">收货人</th>
					<th style="width: 135px;">订单金额</th>
					<th style="width: 48px;text-align:center;">订单时间</th>
					<th style="width: 64px;">状态</th>
					<th style="width: 128px;"></th>
				</tr>
			</thead>   
				
			<tbody role="alert" aria-live="polite" aria-relevant="all">
				<%= render :partial=> "order", :collection => @orders %>
			</tbody>
			<!-- <tfoot>
				<tr>
					<td colspan="6">
						2件商品 总价：120元
										优惠：10元
										总计：10元
					</td>
				</tr>
			</tfoot> -->
		</table>
		<%= link_to "去购物", root_path, :class => "btn btn-danger" %>
		<!-- <%= link_to "去结算", order_pay_path, class:"btn btn-danger" %> -->
	</div>
</div>
<!-- 	<div class="row-fluid">
		<div class="span12">
			<div class="dataTables_info" id="DataTables_Table_0_info">Showing 1 to 10 of 32 entries</div>
		</div>
		<div class="span12 center">
			<div class="dataTables_paginate paging_bootstrap pagination">
				<ul>
					<li class="prev disabled"><a href="#">← Previous</a></li>
					<li class="active"><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">4</a></li>
					<li class="next"><a href="#">Next → </a></li>
				</ul>
			</div>
		</div>
	</div> -->

app/views/order/pay.html.erb
<style type="text/css">
span small {
  font-size: 11px;
  color: #999999;
}
.itemset .item {
	display:inline-block;
	width:300px;
	height:28px;
	line-height:28px;
}
.radio input[type="radio"] {
  float: left;
  margin-left: 0px;
}
.white td {
	background:none;
	border-width:0px;
	text-align:right;
}
</style>

<div style="width:1200px;margin:10px auto;">
	<div style="font-size:20px;border-bottom:1px solid #999999;">填写并确认订单信息</div>
	<div>
		<!-- 收货人信息 -->
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<thead>
				<tr role="row">
					<th><span style="">收货人信息</span></th>
				</tr>
			</thead>   
			<tbody role="alert" aria-live="polite" aria-relevant="all">
				<tr>
					<td><%= @current_user.mail_addresses.first.address %>
					<span style="text-indent:2em;"><strong>邮政编码：</strong><%= @current_user.mail_addresses.first.post_code %></span></td>
				</tr>
			</tbody>
		</table>
		<!-- 支付及配送方式 -->
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<thead>
				<tr role="row">
					<th><span style="">支付及配送方式</span></th>
				</tr>
			</thead>   
			<tbody role="alert" aria-live="polite" aria-relevant="all">
				<tr>
					<td>
						<div><h4>支付方式</h4></div>
						<div class="itemset">
							<div class="item">
								<label class="radio-inline">
									<input type="radio" id="radio1" name="paytype" value="1" checked="checked">
									<span>货到付款</span>
								</label>
							</div>
							<span><small>送货上门后再收款，支持现金、POS机刷卡、支票支付</small></span>
						</div>
						<div class="itemset">
							<div class="item">
								<label class="radio-inline">
									<input type="radio" id="radio2" name="paytype" value="2" disabled>
									<span>在线支付</span>
								</label>
							</div>
							<span><small>即时到帐，支持绝大数银行借记卡及部分银行信用卡</small></span>
						</div>
						<div class="itemset">
							<div class="item">
								<label class="radio-inline">
									<input type="radio" id="radio3" name="paytype" value="3" disabled>
									<span>上门自提</span>
								</label>
							</div>
							<span><small>自提时付款，支持现金、POS刷卡、支票支付</small></span>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div><h4>配送方式</h4></div>
						<div class="itemset">
							<div class="item">
								<label class="radio-inline">
									<input type="radio" id="radio1" name="delivertype" value="1" checked="checked">
									<span>果园快递</span>
								</label>
							</div>
							<span><small>我们会努力尽快配送，但因天气、交通等各类因素影响，您的订单有可能会有延误现象！</small></span>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
		<!-- 商品清单 -->
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<thead>
				<tr role="row">
					<th><span style="">商品清单</span></th>
				</tr>
			</thead>   
			<tbody role="alert" aria-live="polite" aria-relevant="all">
				<tr>
					<td>
						<table class="table table-striped table-bordered " id="DataTables_Table_0"">
							<thead>
								<tr role="row">
									<th style="width: 136px;">商品</th>
									<th style="width: 135px;">单价</th>
									<th style="width: 128px;">数量</th>
									<th style="width: 135px;">规格</th>
									<th style="width: 48px;">优惠</th>
									<th style="width: 64px;">库存</th>
								</tr>
							</thead>   
								
							<tbody role="alert" aria-live="polite" aria-relevant="all">
								<%= render :partial=> "order_item", :collection => @order_items %>
							</tbody>
						</table>
						<div style="float:right">
							<% sum =0 %>
							<% @order_items.each do |item| %>
								<% sum += item.fruit.price_present * item.quantity %>
							<% end %>
							<table class="white">
								<tr>
									<td><%= @order_items.count %>件商品，总价：</td>
									<td><%= sum %>元</td>
								</tr>
								<tr>
									<td>优惠：</td>
									<td><%= discount=0 %>元</td>
								</tr>
								<tr>
									<td>运费：</td>
									<td><%= freight_price=10.0 %>元</td>
								</tr>
								<tr>
									<td>应付总额：</td>
									<td><%= sum + freight_price - discount %>元</td>
								</tr>
							</table>
							<div style="text-align:center;">
								<%= link_to "提交订单", order_pay_success_path, class:"btn btn-danger" %>
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>

		
	</div>
</div>

app/views/order/pay_success.html.erb
<style type="text/css">
span small {
  font-size: 11px;
  color: #999999;
}
.itemset .item {
	display:inline-block;
	width:300px;
	height:28px;
	line-height:28px;
}
.radio input[type="radio"] {
  float: left;
  margin-left: 0px;
}
.white td {
	background:none;
	border-width:0px;
	text-align:right;
}
</style>
<div style="width:1200px;margin:10px auto;">
	<div class="table table-bordered" style="height:60px;font-size:20px;line-height:20px;padding:20px;background:#F5F6E7;border:1px solid #EDD28B;border-radius:0px;">
		<span><strong>订单提交成功，管理员正在为您选购的商品发货，近期请注意快递信息！</strong></span>
	</div>
	<div style="text-align:center;">
		<%= link_to "<<继续购物", root_path, :class => "btn" %>
		<%= link_to "前往查看", order_index_path, class:"btn btn-success" %>
	</div>
</div>

app/views/order/show.html.erb
<table class="table table-striped table-bordered">
	<tr>
		<td>订单Id</td>
		<td><%= @order.id%></td>
	</tr>
	<tr>
		<td>用户</td>
		<td><%= @order.user.username%></td>
	</tr>
	<tr>
		<td>收货人</td>
		<td><%= @order.consignee_name %></td>
	</tr>
	<tr>
		<td>收货地址</td>
		<td><%= @order.consignee_address %></td>
	</tr>
	<tr>
		<td>联系方式</td>
		<td><%= @order.consignee_phone %></td>
	</tr>
	<tr>
		<td>备注</td>
		<td><%= @order.remark %></td>
	</tr>
	<tr>
		<td>订单金额</td>
		<td><%= @order.total_price %></td>
	</tr>
	<tr>
		<td>订单日期</td>
		<td><%= @order.created_at.to_s[0..19] %></td>
	</tr>
	<tr>
		<td>订单状态</td>
		<td><%= @order.status_text %></td>
	</tr>
</table>
<div style="width:100%">
	<div style="text-align:center;">
		<% if @order.status < 9 %>
			<%= button_to "确认收货", {:action=> "order_done", :id=> @order}, :confirm => "请确认已收货！" %>
		<% end %>
	</div>
	<div style="text-align:center;">
		<% if @order.status < 4 %>
			<%= link_to "取消订单", {action:"destroy", id:@order}, confirm:"是否要取消订单？" %>
		<% end %>
	</div>
</div>
<script type="text/javascript">
	$(".button_to input:first").addClass("btn btn-success")
</script>
<div class="label label-success order-item">订单明细</div>
<table class="table table-striped table-bordered">
	<tr>
		<th>商品</th>
		<th>单价</th>
		<th>数量</th>
		<th>规格</th>
		<th>库存</th>
	</tr>

	<%= render :partial=> "order_item", :collection => @order.order_items %>

	</table>
<%= link_to "返回", :action => "index" %>