config/routes.rb
Fruithome::Application.routes.draw do
  root 'fruit#index'
	get "about" => "about#index"
	
	get "login" => "user#login"
	post "login" => "user#login"
	post "register" => "user#register"
	get "register" => "user#register"
	get "user" => "user#index"
	get "logout" => "user#logout"
	get "user/information"
	get "user/security"
	get "user/change_password"
	post "user/change_password"
	get "user/update_mail_address"
	post "user/update_mail_address"
	get "user/edit_info" 
	get "user/edit_security" 
	post "user/update_info"
	post "user/update_security"
	
	
  get "index" => "fruit#index"
  get "search" => "fruit#search"
	get "show" => "fruit#show"
	post "add_to_cart" => "fruit#add_to_cart"
  post "fruit/collect"
	
  get "order/index" => "order#index"
  get "order/show" => "order#show"
  get "order/destroy"
  post "order/order_done"
	get "order/pay" => "order#pay"
	get "order/collection" => "order#collection"
	get "order/pay_success"
	get "order/collection"
	post "order/cancel_collection"
	
	get "cart/show" => "cart#show"
  post "cart/destroy"
	
  get "admin/fruit_type/new" => "admin/fruit_type#new"
  post "admin/fruit_type/create" => "admin/fruit_type#create"
  get "admin/fruit_type/edit"
  post "admin/fruit_type/update"
  post "admin/fruit_type/destroy"
  get "admin/fruit_type/show"
  get "admin/fruit_type" => "admin/fruit_type#index"
	
  get "admin/origin_place/new" => "admin/origin_place#new"
  post "admin/origin_place/create" => "admin/origin_place#create"
  get "admin/origin_place/edit"
  post "admin/origin_place/update"
  post "admin/origin_place/destroy"
  get "admin/origin_place/show"
  get "admin/origin_place" => "admin/origin_place#index"
	
  get "admin/fruit/new" => "admin/fruit#new"
  post "admin/fruit/create" => "admin/fruit#create"
  get "admin/fruit/edit"
  post "admin/fruit/update"
  post "admin/fruit/destroy"
  get "admin/fruit/show"
  get "admin/fruit" => "admin/fruit#index"
	
	get "admin/order/new" => "admin/order#new"
  post "admin/order/create" => "admin/order#create"
  get "admin/order/edit"
  post "admin/order/update"
  post "admin/order/destroy"
  get "admin/order/show"
  get "admin/order/history"
  get "admin/order" => "admin/order#index"
	
	get "admin/login" => "admin/user#login"
	post "admin/login" => "admin/user#login"
	get "admin/logout" => "admin/user#logout"
	get "admin/user/index"
	get "admin/user/information"
	get "admin/user/edit_info"
	post "admin/user/update_info"
	get "admin/user/security"
	get "admin/user/change_password"
	post "admin/user/change_password"
	post "admin/user/update_mail_address"
	get "admin/user/edit_security" 
	post "admin/user/update_security"
	
  get "admin/member/new" => "admin/member#new"
  post "admin/member/create" => "admin/member#create"
  get "admin/member" => "admin/member#index"
  get "admin/member/banned"
  get "admin/member/edit"
  post "admin/member/update"
  post "admin/member/destroy"
  get "admin/member/show"
	
  
  

end

app/views/shared/_ad_and_recommendation_for_index.erb
<style type="text/css">
.ctrwrapper {
	float: center;
	width: 420px;
}
.blk {
	border-right: #999999 1px solid;
	padding-right: 0px;
	border-top: #999999 1px solid;
	padding-left: 0px;
	margin-bottom: 6px;
	padding-bottom: 7px;
	border-left: #999999 1px solid;
	padding-top: 7px;
	border-bottom: #999999 1px solid;
}
#NewsPic { border-top-width: 0px; padding-right: 0px; padding-left: 0px; border-left-width: 0px; left: 0px; border-bottom-width: 0px; padding-bottom: 0px; margin: 0px; width: 368px; padding-top: 0px; position: relative; top: 0px; height: 300px; border-right-width: 0px}
#NewsPicTxt {	border-top-width: 1px; padding-right: 0px; padding-left: 0px; font-weight: bold; border-left-width: 1px; font-size: 12px; border-bottom-width: 1px; padding-bottom: 0px; margin: 3px auto 0px; width: 365px; color: black; padding-top: 0px; font-family: sans-serif; position: relative; height: 0px; text-align: center; border-right-width: 1px}
#NewsPicTxt A {	COLOR: black; TEXT-DECORATION: none}
#NewsPicTxt A:hover {	COLOR: black; TEXT-DECORATION: none}
#NewsPicTxt A:visited {	COLOR: black; TEXT-DECORATION: none}
#NewPicTxt A:link {	COLOR: black; TEXT-DECORATION: none}
#NewsPicTxt A:hover {	COLOR: red}
#NewsPic A {	BORDER-TOP-WIDTH: 0px; BORDER-LEFT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px; TEXT-DECORATION: none}
#NewsPic A:hover {	TEXT-DECORATION: none}
#NewPic A:visited {	TEXT-DECORATION: none}
#NewsPic .Picture {	BORDER-RIGHT: #ffffff 1px solid; BORDER-TOP: #ffffff 1px solid; LEFT: 0px; BORDER-LEFT: #ffffff 1px solid; WIDTH: 100%; BORDER-BOTTOM: #ffffff 1px solid; POSITION: absolute; TOP: 0px; HEIGHT: 100%}
#NewsPic .Nav {	RIGHT: 0px; WIDTH: 100%; BOTTOM: 0px; POSITION: absolute; HEIGHT: 12px}
#NewsPic .Nav span {	display: block; background: #000000; float: right; font: 10px courier; border-left: #ffffff 1px solid; width: 25px; cursor: hand; color: #ffffff; height:25px;line-height:25px; text-align: center; border-radius:50%; }
#NewsPic .Nav span.Cur {	background: #40AF39; color: white}
#NewsPic .Nav span.Normal {	BACKGROUND: #000000; FILTER: Alpha(opacity=50); COLOR: white; opacity: .5}
#NewsPic .Nav span A {	DISPLAY: block; WIDTH: 100%; COLOR: white; POSITION: relative; HEIGHT: 100%}
#NewsPic .Nav span A:hover {	CURSOR: hand}
#NewsPic img {
	border-radius:0px;
}
.Nav span {
	border-radius:50%;
	height:25px;
	width:25px;
	line-height:25px;
	background-color:#40AF39;
}
</style>

<!-- show_images -->
<%= javascript_include_tag "floatPic", "data-turbolinks-track" => true %>

<div id="flashbox" style="position:relative; width:100%">
	<div class="flash" style="margin:0px auto; width:1200px; height:370px;">
		<!-- flashbox(首页轮换图) -->
		<table border="0" cellpadding="0" cellspacing="0" style="text-align:center;">
			<tr>
				<td><div class=auto_2_left_1_2 style="margin-top: 0px; width:100%; height:100%">
					<span id=focuspic>
						<div id=NewsPic style="width:900px;height:300px;">
							<!-- <a href="" target=_blank><%= image_tag "show_images/1.jpg" %></a> -->
							<a href="http://localhost:3000/show?id=71" target=_blank><%= image_tag "show_images/2.jpg" %></a>
							<a style="DISPLAY: none" href="http://localhost:3000/show?id=70" target=_blank><%= image_tag "show_images/3.jpg" %></a>
							<a style="DISPLAY: none; VISIBILITY: hidden" href="http://localhost:3000/show?id=72" target=_blank><%= image_tag "show_images/4.jpg" %></a>
							<a style="DISPLAY: none; VISIBILITY: hidden" href="http://localhost:3000/show?id=13" target=_blank><%= image_tag "show_images/5.jpg" %></a>
						</div>
						<div id=NewsPicTxt style="DISPLAY: none; VISIBILITY: hidden"></div>
					</span>
				<script language=javascript>init();</script>
				</div></td>
				<td style="width:300px;">
					<table class="table table-striped table-bordered" style="width:280px;float:right;margin:10px 5px;">
						<tr><td style="text-align:center;">
							<span>近日最火</span>
						</td></tr>
						<tr><td style="text-align:center;">
							<%= link_to :action => "show", :id => @fruit_special do %>
								<%= image_tag "fruit_images/#{@fruit_special.id}_270_270_1.jpg", style:"width:200px;height:200px;margin-left:10px;display:block;" %>
								<%= @fruit_special.name %>
							<% end %>
						</td></tr>
					</table>
				</td>
			</tr>

		</table>
	</div>
</div>

app/views/shared/_crumb.erb
<style type="text/css">
.breadcrumb {
	background: white;
	border-width: 0px;
}
.breadcrumb a {
	color:black;
}
.breadcrumb>li+li:before {
	content: ">";
	padding: 0 5px;
	color: #ccc;
}
</style>
<div>
	<div>
		<ol class="breadcrumb">
			<li><strong><%= link_to "首页", "/" %></strong></li>
			<% if @fruit %>
				<% if @fruit.fruit_type %>
					<li><%= link_to @fruit.fruit_type.name, controller:"fruit", action:"search", key_word:@fruit.fruit_type.name %></li>
				<% end %>
				<li class="active"><%= @fruit.name %></li>
			<% elsif @key_word %>
				<li><%= @key_word.blank? ? "所有商品" : @key_word %></li>
			<% end %>
		</ol>
		<!--<!--%= link_to "首页", "/" %>
		<span>></span>
		<span><a href="#"><!--%= @fruit.fruit_type.name %></a></span>
		<span>></span>
		<span><!--%= @fruit.name %></span> -->
	</div>
</div>

app/views/shared/_fruit_blank.erb
<div class="table table-bordered" style="margin:15px;height:60px;font-size:20px;line-height:20px;padding:20px;background:#F5F6E7;border:1px solid #EDD28B;border-radius:0px;">
	<span><strong>抱歉，没有找到与“<span style="color:red;"><%= @key_word %></span>”相关的商品。请更换关键词进行搜索。</strong></span>
</div>

app/views/shared/_fruit_search.erb
<div class="fl table table-bordered" style="width:240px; height:400px;margin:15px;">
	<div class="" style="">
		<%= link_to :action => "show", :id => fruit_search do %>
			<%= image_tag "fruit_images/#{fruit_search.id}_270_270_1.jpg", :width => "250px", :alt =>"#{fruit_search.name}" %>
		<% end %>
	</div>
	<div style="">
		<ul style="margin: 0 0 9px 15px;">
			<li style="width:200px;height:20px;">
				<%= link_to :action => "show", :id => fruit_search do %>
					<strong><%= fruit_search.name %></strong>
				<% end %>
			</li>
			<li style="width:200px;height:30px;"><span style="display:block;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;"><%= fruit_search.brief_introduction %></span></li>
			<li style="width:200px">
				<span ><%= fruit_search.price_present %></span>
				<span>/</span>
				<span style=""><%= fruit_search.unit %></span>
			</li>
			<li>
				<% op=fruit_search.origin_place %>
				<span style="display:block;"><%= op ? op.name : "" %></span>
			</li>
		</ul>
	</div>
</div>

app/views/shared/_global_top_bar.erb
<style type="text/css">
.self-center ul li a, .website ul li a {
	padding-left:0px;
}
</style>
<div id="global_top_bar">
	<div id="global_top_nav" class="global_top_nav">
		<ul class="top_nav_left">
			<% if current_user %> 
				<li><span>您好，<%= link_to current_user.username, user_information_path %></span></li>
				<li><span><%= link_to "退出", logout_path %></span></li>
			<% else %> 
				<li><span><%= link_to "亲，请登录", login_path %></span></li>
				<li><span><%= link_to "免费注册", register_path %></span></li>
			<% end %>
		</ul>
		
		<ul class="top_nav_right">
			<li class="btn-group">
				<div class="self-center">
					<span class="dropdown-toggle" data-toggle="dropdown"><a>个人中心</a><i class="icon-chevron-down"></i></span>
					<ul class="dropdown-menu">
						<li>
							<%= link_to order_index_path do %>
								<i class="icon-star"></i>
								<span>我的订单</span>
							<% end %>
						</li>
						<li>
							<%= link_to user_information_path do %>
								<i class="icon-star"></i>
								<span>我的账户</span>
							<% end %>
						</li>
						<!-- <li><a href="#"><i class="icon-tag"></i> 我的优惠</a></li> -->
						<li class="divider"></li>
						<li>
							<%= link_to logout_path do %>
								<i class="icon-tint"></i>
								<span>退出</span>
							<% end %>
						</li>
					</ul>
				</div>
			</li>
			<li class="btn-group">
				<span class=""><%= link_to "我的收藏夹", order_collection_path %></span>
				<!-- <span class="dropdown-toggle" data-toggle="dropdown"><a href="#">我的收藏夹</a><i class="icon-chevron-down"></i></span>
				<ul class="dropdown-menu">
					<li><a href="#"><i class="icon-star"></i>水果</a></li>
					<li><a href="#"><i class="icon-star"></i>类别</a></li>
				</ul> -->
			</li>
			<li class="">
				<span class=""><a href="http://localhost:3000/search">所有商品</a></span>
			</li>
			<li class="">
				<span class=""><a href="http://localhost:3000/user/information">客户中心</a></span>
			</li>
			<li class="btn-group">
				<div class="website">
					<span class="dropdown-toggle" data-toggle="dropdown"><a href="#">网站导航</a><i class="icon-chevron-down"></i></span>
					<ul class="dropdown-menu">
						<li>
							<%= link_to root_path do %>
								<i class="icon-star"></i>水果之家
							<% end %>
						</li>
						<li>
							<%= link_to "http://www.taobao.com" do %>
								<i class="icon-star"></i>淘宝
							<% end %>
						</li>
						<li>
							<%= link_to admin_user_index_path do %>
								<i class="icon-user"></i>我是管理员
							<% end %>
						</li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>

app/views/shared/_left_menue.erb
<style type="text/css">
.nav .nav-header {
  font-size: 20px;
  line-height: 25px;
  color: black;
}
</style>
<div class="span2 main-menu-span" style="margin:0;">
	<div class=" nav-collapse sidebar-nav">
		<ul class="nav nav-tabs nav-stacked main-menu">
			<li class="nav-header hidden-tablet">订单中心</li>
			<li><%= link_to "我的订单", order_index_path %></li>
			<li><%= link_to "我的收藏", order_collection_path %></li>
			<!-- <li><a class="ajax-link" href="form.html"><span class="hidden-tablet"> 浏览历史</span></a></li>
			<li><a class="ajax-link" href="chart.html"><span class="hidden-tablet"> 为我推荐</span></a></li> -->
			<li class="nav-header hidden-tablet">账户中心</li>
			<li><%= link_to "账户信息", user_information_path %></li>
			<li><%= link_to "账户安全", user_security_path %></li>
			<li><%= link_to "修改密码", user_change_password_path %></li>
			<!-- <li><%= link_to "账户余额" %></li> -->
			<li><%= link_to "收货地址", user_update_mail_address_path %></li>
			<!-- <li class="nav-header hidden-tablet">客户服务</li>
			<li><a class="ajax-link" href="table.html"><span class="hidden-tablet"> 退换货</span></a></li>
			<li><a class="ajax-link" href="calendar.html"><span class="hidden-tablet"> 取消订单记录</span></a></li>
			<li><a class="ajax-link" href="grid.html"><span class="hidden-tablet"> 我的投诉</span></a></li>
			<li class="nav-header hidden-tablet">社区中心</li>
			<li><a class="ajax-link" href="table.html"><span class="hidden-tablet"> 商品评价/晒单</span></a></li>
			<li><a class="ajax-link" href="calendar.html"><span class="hidden-tablet"> 购买咨询</span></a></li> -->
		</ul>
		<!-- <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox"> Ajax on menu</label> -->
	</div><!--/.well -->
</div><!--/span-->

app/views/shared/_site_header_for_search_and_type.erb
<div id="site_header">
	<div class="header_wrapper">
		<div class="hd_logo fl">
			<a href="http://localhost:3000/"><%= image_tag "fruit_home_logo.png", width:"175px" %></a>
		</div>
		<div class="hd_search fl">
			<div class="hd_search_form">
				<form action="http://localhost:3000/search">
				<div class="input-group">
					<input type="text" placeholder="请输入关键词" name="key_word" class="form-control" style="width:250px;"></input>
					<input type="submit" value="搜索" class="btn btn-default"></input>
				</div>
				</form>
			</div>
			<p id="hot_keyword" class="hd_hot_keyword_search">
				<span>果友都在找：</span>
				<!-- put the hot word here, 存放热词数组 -->
				<% ["苹果","梨子","送礼","礼包","春季","特惠","学生"].each do |word| %>
					<%= link_to word, search_path, key_word:word %>
				<% end %>
			</p>
		</div>
		<div class="hd_banner fl">
			<div class="cart">
				<div class="btn-group">
					<button type="button" class="btn btn-type-nav">
					<span class="icon32 icon-orange icon-cart"></span>
					<%= link_to cart_show_path, style: "color:white;" do %>
						<span>我的购物车 </span>
						<span class="notification red"><%= @cart.order_items.length %></span>
					<% end %>
					</button>
				</div>
			</div>
		</div>
	</div>
</div>


<style type="text/css">
.btn-group button {
	font-size:20px;
	letter-spacing:5px;
}
</style>
<div id="hd_nav">
	<div class="fruit_type">
		<div class="fruit_type_nav fl">
			<div class="btn-group">
				<button type="button" class="btn btn-type-nav" onclick="location.href='http://localhost:3000/'">
					水果之家
				</button>
			</div>	
			<% FruitType.where( :super_id => nil ).each do |suptype| %>
				<div class="btn-group">
					<button type="button" class="btn btn-type-nav dropdown-toggle" data-toggle="dropdown">
						<%= suptype.name %>
						<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<% FruitType.where( :super_id => suptype.id ).each do |subtype| %>
							<li>
								<%= link_to subtype.name, controller:"fruit", action:"search", key_word:subtype.name %>
							</li>
						<% end %>
					</ul>
				</div>	
			<% end %>
			<div class="btn-group">
				<button type="button" class="btn btn-type-nav dropdown-toggle" data-toggle="dropdown">
					国内鲜果
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<% OriginPlace.where( :super_id => 1 ).each do |subtype| %>
						<li>
							<%= link_to subtype.name, controller:"fruit", action:"search", key_word:subtype.name %>
						</li>
					<% end %>
				</ul>
			</div>	
			<div class="btn-group">
				<button type="button" class="btn btn-type-nav dropdown-toggle" data-toggle="dropdown">
					进口鲜果
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<% OriginPlace.where( :super_id => nil ).where.not(name: "中国大陆").each do |subtype| %>
						<li>
							<%= link_to subtype.name, controller:"fruit", action:"search", key_word:subtype.name %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>