config/routes.rb
Fruithome::Application.routes.draw do
  root 'fruit#index'
	get "about" => "about#index"
	
	get "login" => "user#login"
	post "login" => "user#login"
	post "register" => "user#register"
	get "register" => "user#register"
	get "user" => "user#index"
	get "logout" => "user#logout"
	get "user/information"
	get "user/security"
	get "user/change_password"
	post "user/change_password"
	get "user/update_mail_address"
	post "user/update_mail_address"
	get "user/edit_info" 
	get "user/edit_security" 
	post "user/update_info"
	post "user/update_security"
	
	
  get "index" => "fruit#index"
  get "search" => "fruit#search"
	get "show" => "fruit#show"
	post "add_to_cart" => "fruit#add_to_cart"
  post "fruit/collect"
	
  get "order/index" => "order#index"
  get "order/show" => "order#show"
  get "order/destroy"
  post "order/order_done"
	get "order/pay" => "order#pay"
	get "order/collection" => "order#collection"
	get "order/pay_success"
	get "order/collection"
	post "order/cancel_collection"
	
	get "cart/show" => "cart#show"
  post "cart/destroy"
	
  get "admin/fruit_type/new" => "admin/fruit_type#new"
  post "admin/fruit_type/create" => "admin/fruit_type#create"
  get "admin/fruit_type/edit"
  post "admin/fruit_type/update"
  post "admin/fruit_type/destroy"
  get "admin/fruit_type/show"
  get "admin/fruit_type" => "admin/fruit_type#index"
	
  get "admin/origin_place/new" => "admin/origin_place#new"
  post "admin/origin_place/create" => "admin/origin_place#create"
  get "admin/origin_place/edit"
  post "admin/origin_place/update"
  post "admin/origin_place/destroy"
  get "admin/origin_place/show"
  get "admin/origin_place" => "admin/origin_place#index"
	
  get "admin/fruit/new" => "admin/fruit#new"
  post "admin/fruit/create" => "admin/fruit#create"
  get "admin/fruit/edit"
  post "admin/fruit/update"
  post "admin/fruit/destroy"
  get "admin/fruit/show"
  get "admin/fruit" => "admin/fruit#index"
	
	get "admin/order/new" => "admin/order#new"
  post "admin/order/create" => "admin/order#create"
  get "admin/order/edit"
  post "admin/order/update"
  post "admin/order/destroy"
  get "admin/order/show"
  get "admin/order/history"
  get "admin/order" => "admin/order#index"
	
	get "admin/login" => "admin/user#login"
	post "admin/login" => "admin/user#login"
	get "admin/logout" => "admin/user#logout"
	get "admin/user/index"
	get "admin/user/information"
	get "admin/user/edit_info"
	post "admin/user/update_info"
	get "admin/user/security"
	get "admin/user/change_password"
	post "admin/user/change_password"
	post "admin/user/update_mail_address"
	get "admin/user/edit_security" 
	post "admin/user/update_security"
	
  get "admin/member/new" => "admin/member#new"
  post "admin/member/create" => "admin/member#create"
  get "admin/member" => "admin/member#index"
  get "admin/member/banned"
  get "admin/member/edit"
  post "admin/member/update"
  post "admin/member/destroy"
  get "admin/member/show"
	
  
  

end

app/models/user.rb
# -*- encoding: utf-8 -*-
class User < ActiveRecord::Base
	has_secure_password validations: false
	# before_create :password_validation
	
	has_many	:collections
	has_many	:consultations
	has_many	:comments
	has_many	:orders
	has_many	:mail_addresses
	has_many	:accounts
	
	USERNAME_MIN_LENGTH = 2
	USERNAME_MAX_LENGTH = 20
	USERNAME_RANGE = USERNAME_MIN_LENGTH..USERNAME_MAX_LENGTH
	PASSWORD_MIN_LENGTH = 6
	PASSWORD_MAX_LENGTH = 20
	PASSWORD_RANGE = PASSWORD_MIN_LENGTH..PASSWORD_MAX_LENGTH
	e_mail_MAX_LENGTH = 30
	
	validates :username, 
						:presence => {:message => '请输入用户名'}, 
						:uniqueness => {:message => '用户名已注册，请更换'},
						:format => {:with => /\A[a-z]{#{USERNAME_MIN_LENGTH},#{USERNAME_MAX_LENGTH}}\z/i,
												:message => '用户名格式：应由2-20位大小写英文字符组成！'}
	validates :e_mail, 
						# :presence => {:message => '请输入邮箱'}, 
						:uniqueness => {:message => '邮箱已注册，请更换'},
						:format => {:with => /\A([A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4})\z/i,
												:message => "请输入正确的邮箱！"}
	# 密请使用大小写字母和数字
	validates :password,
						:format => {:with => /\A[a-z0-9]{#{PASSWORD_MIN_LENGTH},#{PASSWORD_MAX_LENGTH}}\z/i,
												:message => "密码格式：应由6-20位大小写英文字符和数字组成！"}	,
						:confirmation => {:if => :password_changed?,
															:message => "密码确认失败"}	
	
	def password_validation
		if self.password != self.password_confirmation
			self.errors.add( :password, self.password)
			self.errors.add( :password_confirmation, "密码确认不匹配")
			false
		end
	end
	
	def password_changed?
		self.password != self.password_confirmation
	end
end

app/controllers/admin/user_controller.rb
# -*- encoding: utf-8 -*-
class Admin::UserController < ApplicationController
	include ApplicationHelper
	before_filter :admin_login_required,  :except => [:login,:logout]
	layout :determine_layout
  # layout "empty", :only => [:register, :login]
	# layout "self_center", :except => [:register, :login, :logout]
	def index
	@page_title = "管理员"
	flash[:alert] = ""
	end
	
	def login
		@page_title = "用户登陆"
		flash[:alert] = ""
		# return unless request.post?
		unless request.post?
			# flash[:alert] = "非post，即get"
			return 
		end
		# unless params[:login]
			# flash[:alert] << "kong"
			# return
		# end
		username = params[:login]
		admin_user = AdminUser.where("username = ? or e_mail =?",username,username).first		
		unless admin_user
			flash[:alert] = "用户未注册"
			return
		end
		# flash[:alert] << admin_user.to_yaml
		# self.current_user = user.password_text == params[:password]
		self.current_admin_user = admin_user.authenticate(params[:password])
		# flash[:alert] << current_admin_user.to_yaml
		if current_admin_user
			flash[:notice] = "Logged in successfully".to_s
			# current_user.update_columns({"latest_log_date" => Time.new.getlocal})
			redirect_back_or_default(:controller => 'admin/user', :action => 'index')
		else
			flash[:alert] == "密码错误"
			render :action => "login"
		end
	end
	
	def logout 
		# self.current_user.forget_me if logged_in?
		cookies.delete :auth_token
		reset_session
		flash[:notice] = "You have been logged out."
		redirect_back_or_default(:controller => '/user', :action => 'login')
	end

	def security
	end

	def change_password
		if request.post? and params[:password] and @current_admin_user.authenticate(params[:password][:password_old])
			@current_admin_user.password = params[:password][:password]
			if params[:password][:password] == params[:password][:password_confirmation] && @current_admin_user.save
				flash[:alert] = "<div class='errors'><h5>密码修改成功</h5></div>".html_safe #"注册成功"
				redirect_to :action => "change_password"
			else
				flash[:alert] = errors_for(@current_admin_user, "修改失败，请检查：").html_safe
			end
		end
		# flash.now[:notice] = "Incorrect login!" 
	end

	def edit_security
	end
	
	def update_info
		flash[:alert] =""
		if request.post? and params[:admin_user]
			if @current_admin_user.update_columns(admin_user_update_params)
				flash[:notice] = admin_user_update_params[:username].to_s #"更新成功"
				redirect_to :action => "information"
			else
				flash[:alert] = errors_for(@current_admin_user, "抱歉，请检查输入信息：").html_safe
				render :action => "edit_info"
			end
		end
	end
	
	def update_security
		flash[:alert] =""
		if request.post? and params[:user]
			if @current_user.update_columns(user_update_params)
				# flash[:notice] = user_update_params[:username].to_s #"更新成功"
				redirect_to :action => "security"
			else
				flash[:alert] = errors_for(@current_user, "抱歉，请检查输入信息：").html_safe
				render :action => "edit_security"
			end
		end
	end
		
	private
	def user_params
		params.require(:user).permit(:username,:e_mail,:password,:password_confirmation)
	end
	
	def admin_user_update_params
		params.require(:admin_user).permit(:username, :e_mail, :phone_number)
	end
	
	def determine_layout
		if admin_logged_in? 
			"admin_layout"
		else 
			"empty"
		end
	end
end

app/controllers/user_controller.rb
# -*- encoding: utf-8 -*-
class UserController < ApplicationController
	include ApplicationHelper
	before_filter :login_required,  :except => [:register, :login, :logout]
	layout :determine_layout
  # layout "empty", :only => [:register, :login]
	# layout "self_center", :except => [:register, :login, :logout]
	def index
	@page_title = "个人中心"
	end
	
	def register
		@page_title = "欢迎注册"
		flash[:alert] = ""
		if request.post? and params[:user]
			@user = User.new(user_params)
			@user.status = "1"
			if params[:user][:password] == params[:user][:password_confirmation] && @user.save
				flash[:notice] = user_params[:username].to_s #"注册成功"
				redirect_to :action => "index",  :controller=>"fruit"
			else
				flash[:alert] = errors_for(@user, "注册失败，请检查：").html_safe
			end
		end
	end
	
	def login
		@page_title = "用户登陆"
		flash[:alert] = ""
		return unless request.post?
		username = params[:login]
		user = User.where("username = ? or e_mail =?",username,username).first		
		unless user
			flash[:alert] = "用户未注册或被屏蔽" 
			return
		end
		if user.status.eql? 0
			flash[:alert] = "用户已屏蔽，请联系管理员" 
			return
		end
		# self.current_user = user.password_text == params[:password]
		self.current_user = user.authenticate(params[:password])
		if current_user
			if params[:remember_me] == "1"
				self.current_user.remember_me
				cookies[:auth_token] = { :value => self.current_user.remember_token , :expires => self.current_user.remember_token_expires_at }
			end
			# flash[:notice] = "Logged in successfully".to_s
			current_user.update_columns({"latest_log_date" => Time.new.getlocal})
			redirect_back_or_default(:controller => '/fruit', :action => 'index')
		else
			flash[:alert] = "密码错误"
			render :action => "login"
		end
		# flash.now[:notice] = "Incorrect login!" 
	end
	
	def logout 
		# self.current_user.forget_me if logged_in?
		cookies.delete :auth_token
		reset_session
		flash[:notice] = "You have been logged out."
		redirect_back_or_default(:controller => '/fruit', :action => 'index')
	end

	def information
	end

	def security
	end

	def change_password
		if request.post? and params[:password] and @current_user.authenticate(params[:password][:password_old])
			@current_user.password = params[:password][:password]
			if params[:password][:password] == params[:password][:password_confirmation] && @current_user.save
				flash[:alert] = "<div class='errors'><h5>密码修改成功</h5></div>".html_safe #"注册成功"
				redirect_to :action => "change_password"
			else
				flash[:alert] = errors_for(@current_user, "修改失败，请检查：").html_safe
			end
		end
		# flash.now[:notice] = "Incorrect login!" 
	end

	def update_mail_address
		if request.post? and params[:mail_addresses]
		@current_user.mail_addresses
		params[:mail_addresses].each_slice(2) do |mail_add|
			if mail_add[0][0].split("_").length <= 1
				MailAddress.create!(user_id:@current_user.id, address:mail_add[0][1], post_code:mail_add[1][1]) if not mail_add[0][1].eql? ""
			else
				ma = MailAddress.find(mail_add[0][0].split("_")[1])
				ma.update(address:mail_add[0][1], post_code:mail_add[1][1]) unless mail_add[0][1].eql?(ma.address) and mail_add[1][1].eql?(ma.post_code)
			end
		end
		end
	end
	
	def edit_info
	end
	
	def edit_security
	end
	
	def update_info
		flash[:alert] =""
		if request.post? and params[:user]
			if @current_user.update_columns(user_update_params)
				flash[:notice] = user_update_params[:username].to_s #"更新成功"
				redirect_to :action => "information"
			else
				flash[:alert] = errors_for(@current_user, "抱歉，请检查输入信息：").html_safe
				render :action => "edit_info"
			end
		end
	end
	
	def update_security
		flash[:alert] =""
		if request.post? and params[:user]
			if @current_user.update_columns(user_update_params)
				# flash[:notice] = user_update_params[:username].to_s #"更新成功"
				redirect_to :action => "security"
			else
				flash[:alert] = errors_for(@current_user, "抱歉，请检查输入信息：").html_safe
				render :action => "edit_security"
			end
		end
	end
		
	private
	def user_params
		params.require(:user).permit(:username,:e_mail,:password,:password_confirmation)
	end
	
	def user_update_params
		params.require(:user).permit(:username, :real_name, :sex, :birthdate, :e_mail, :phone_number, :city, :question, :answer)
	end
	
	def determine_layout
		if logged_in? 
			"self_center"
		else 
			"empty"
		end
	end
end

app/views/admin/user/change_password.html.erb
<div style="margin:10px auto;">
	<div style="font-size:30px;padding-top:7px;border-bottom:1px solid #999999;">修改密码</div>
	<div>	
<% if flash[:alert] %>
	<%= flash[:alert] %>
<% end %>
	<%= form_for :password, url:{action:"change_password"} do |f| %>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<tr role="row"><th>原始密码</th></tr>
			<tr><td><%= f.password_field :password_old %><span style="color:red;">请先输入正确的原始密码</span></td></tr>
			<tr><th>新密码</th></tr>
			<tr><td><%= f.password_field :password %></td></tr>
			<tr><th>确认新密码</th></tr>
			<tr><td><%= f.password_field :password_confirmation %></td></tr>
		</table>
		<div style="text-align:center;">
			<%= submit_tag "保存", :class => "submit btn btn-success" %>
		</div>
	<% end %>
		
		
	</div>
</div>

app/views/admin/user/edit_info.html.erb
<div style="margin:10px auto;">
<% if flash[:alert] %>
	<%= flash[:alert] %>
<% end %>
	<div style="font-size:30px;padding-top:7px;border-bottom:1px solid #999999;">编辑个人信息</div>
	<div>	
	<%= form_for :admin_user, url:{action:"update_info"} do |f| %>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<tr role="row">
				<td>用户名</td>
				<td><%= f.text_field :username, value:@current_admin_user.username %></td>
			</tr>
			<tr>
				<td>管理员类型</td>
				<td><%= f.text_field :e_mail, value:@current_admin_user.admin_type, disabled:true %></td>
			</tr>
			<tr>
				<td>邮箱</td>
				<td><%= f.text_field :e_mail, value:@current_admin_user.e_mail %></td>
			</tr>
			<tr>
				<td>联系电话</td>
				<td><%= f.phone_field :phone_number, value:@current_admin_user.phone_number %></td>
			</tr>
			<tr>
		</table>
		<div style="text-align:center;">
			<%= submit_tag "保存", :class => "submit btn btn-success" %>
		</div>
	<% end %>
		
		
	</div>
</div>

app/views/admin/user/edit_security.html.erb
<div style="margin:10px auto;">
<% if flash[:alert] %>
	<%= flash[:alert] %>
<% end %>
	<div style="font-size:30px;padding-top:7px;border-bottom:1px solid #999999;">编辑安全问题</div>
	<div>	
	<%= form_for :user, url:{action:"update_security"} do |f| %>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
			<tr role="row"><th>安全问题</th></tr>
			<tr><td><%= f.text_field :question, value:@current_user.question %></td></tr>
			<tr><th>答案</th></tr>
			<tr><td><%= f.text_field :answer, value:@current_user.answer %></td></tr>
		</table>
		<div style="text-align:center;">
			<%= submit_tag "保存", :class => "submit btn btn-success" %>
		</div>
	<% end %>
		
		
	</div>
</div>

app/views/admin/user/index.html.erb
<style type="text/css">
.label-important {
	 margin: 0 5px;
}
</style>
<% user_all = User.all.count %>
<% user_new = User.where("DATE(created_at) = DATE(?)", Time.now).count %>

<% order_all = Order.all.count %>
<% order_new = Order.where("DATE(created_at) = DATE(?)", Time.now).count %>

<% sales_all = Order.sum(:total_price) %>
<% sales_new = Order.where("DATE(created_at) = DATE(?)", Time.now).sum(:total_price) %>

<% consultation_all = Consultation.all.count %>
<% consultation_new = Consultation.where("DATE(created_at) = DATE(?)", Time.now).count %>

<% comment_all = Comment.all.count %>
<% comment_new = Comment.where("DATE(created_at) = DATE(?)", Time.now).count %>

<div class="sortable row-fluid">
	<a data-rel="tooltip" title="6 new members." class="well span3 top-block" href="#">
		<span class="icon32 icon-red icon-user"></span>
		<div>会员总数</div>
		<div><%= user_all %></div>
		<span class="notification"><%= user_new %></span>
	</a>

	<a data-rel="tooltip" title="4 new pro members." class="well span3 top-block" href="#">
		<span class="icon32 icon-color icon-star-on"></span>
		<div>订单总数</div>
		<div><%= order_all%></div>
		<span class="notification green"><%= order_new %></span>
	</a>

	<a data-rel="tooltip" title="$34 new sales." class="well span3 top-block" href="#">
		<span class="icon32 icon-color icon-cart"></span>
		<div>销售额</div>
		<div><%= sales_all %></div>
		<span class="notification yellow"><%= sales_new %></span>
	</a>
	
<!-- 	<a data-rel="tooltip" title="12 new messages." class="well span3 top-block" href="#">
		<span class="icon32 icon-color icon-envelope-closed"></span>
		<div>留言、评论</div>
		<div><%= consultation_all + comment_all %></div>
		<span class="notification red"><%= comment_new + consultation_new %></span>
	</a> -->
</div>
<div class="row-fluid">
	<div class="box span12">
		<div class="box-content">
			<h3><%= @current_admin_user.username %><small><span id="datetime"></span></small></h3>
			<p style="text-indent:2em;margin-top:30px;">今天一共有个<span class="label label-important"><%= user_new %></span>新会员，<span class="label label-important"><%= order_new %></span>张新订单，今天的销售额是<span class="label label-important"><%= sales_new %></span>元<!-- ，有<span class="label label-important"><%= consultation_new %></span>条留言和<span class="label label-important"><%= comment_new %></span>条评论待处理 --></p>
			<div class="clearfix"></div>
		</div>
	</div>
</div>
<script type="text/javascript">
function startTime() {
	var today=new Date()
	var y=today.getFullYear()
	var mon=today.getMonth() + 1
	var d=today.getDate()
	var w=today.getDay()
	var h=today.getHours()
	var m=today.getMinutes()
	var s=today.getSeconds()
	// add a zero in front of numbers<10
	m=checkTime(m)
	s=checkTime(s)
	var weekday = {
		0:"天",
		1:"一",
		2:"二",
		3:"三",
		4:"四",
		5:"五",
		6:"六"
	}
	document.getElementById('datetime').innerHTML="今天是"+y+"年"+mon+"月"+d+"日，"+"星期"+weekday[w]+"，现在是"+h+"时"+m+"分"+s+"秒"
	t=setTimeout('startTime()',1000)
}
function checkTime(i) {
	if (i<10) {i="0" + i}
	return i
}
startTime()
</script>

app/views/admin/user/information.html.erb
<div style="margin:10px auto;">
	<div style="font-size:30px;padding-top:7px;border-bottom:1px solid #999999;">个人信息</div>
	<div>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
				<tr role="row">
					<td>用户名</td>
					<td><%= @current_admin_user.username %></td>
				</tr>
				<tr>
					<td>管理员类型</td>
					<td><%= @current_admin_user.admin_type %></td>
				</tr>
				<tr>
					<td>邮箱</td>
					<td><%= @current_admin_user.e_mail %></td>
				</tr>
				<tr>
					<td>联系电话</td>
					<td><%= @current_admin_user.phone_number %></td>
				</tr>
				<tr>
					<td>最近登录</td>
					<td><%= @current_admin_user.latest_log_date.to_s[0..19] %></td>
				</tr>
		</table>
		<div style="text-align:center;">
			<%= link_to "编辑", admin_user_edit_info_path %>
		</div>
	</div>
</div>

app/views/admin/user/login.html.erb
<style type="text/css">
form {
	 margin: 0 auto;
	 padding:30px 0;
	 width: 400px;
	 font-size: 20px; 
	 text-align:center;
}
form .form-control {
	width:270px;
}
.login-box .btn {
	width:150px
}
.submit {
	margin-left:17px;
}
</style>
<div style="width:1000px;margin:0 auto" class="login-box">
	<div style="width:100%;" class="login-box-wrapper">
		<div style="height:40px;line-height:40px;background:#40AF39;width:100%;margin:20px auto;" class="login-box-title">
			<h4><a style="font-size:20px;padding:10px;display:inline-block;color:white;text-decoration:none;" href="http://localhost:3000">水果之家FRUITHOME</a></h4>
		</div>
		<div style="width:100%;height:450px;" class="login-content">
			<div style="float:left;width:600px;padding:5px 0 10px 50px;" class="login-left">
				<h4 style="border-bottom:2px solid #40AF39;height:35px;">管理员登录</h4>
				<div class="errors">
				<% if flash[:alert] %>
					<%= flash[:alert] %>
				<% end %>
				</div>
				<%= form_tag %>
					<p><span for="login">管理员：</span>
					<%= text_field_tag 'login', nil, class:"form-control", placeholder:"邮箱/用户名" %></p>

					<p><span for="password">密&nbsp;&nbsp;&nbsp;码：</span>
					<%= password_field_tag 'password', nil, class:"form-control" %></p>

					<!-- <p><span for="remember_me">记住密码：</span>
					<%= check_box_tag 'remember_me', "p", "true" %></p> -->
					
					<%= submit_tag "登录", :class => "submit btn btn-success" %>
					<a href="#" style="vertical-align:bottom;text-decoration:none;font-size:16px;">忘记密码</a>
			</div>
		</div>
	</div>
</div>

app/views/admin/user/security.html.erb
<div style="margin:10px auto;">
	<div style="font-size:30px;padding-top:7px;border-bottom:1px solid #999999;">账户安全</div>
	<div>
		<table class="table table-striped table-bordered " id="DataTables_Table_0"">
				<tr role="row"><th>安全问题</th></tr>
				<tr><td><%= @current_user.question %></td></tr>
				<tr><th>答案</th></tr>
				<tr><td><%= "*" * @current_user.answer.length %></td>
				</tr>
		</table>
		<div style="text-align:center;">
			<%= link_to "编辑", :action=> "edit_security" %>
		</div>
	</div>
</div>