config/routes.rb
Fruithome::Application.routes.draw do
  root 'fruit#index'
	get "about" => "about#index"
	
	get "login" => "user#login"
	post "login" => "user#login"
	post "register" => "user#register"
	get "register" => "user#register"
	get "user" => "user#index"
	get "logout" => "user#logout"
	get "user/information"
	get "user/security"
	get "user/change_password"
	post "user/change_password"
	get "user/update_mail_address"
	post "user/update_mail_address"
	get "user/edit_info" 
	get "user/edit_security" 
	post "user/update_info"
	post "user/update_security"
	
	
  get "index" => "fruit#index"
  get "search" => "fruit#search"
	get "show" => "fruit#show"
	post "add_to_cart" => "fruit#add_to_cart"
  post "fruit/collect"
	
  get "order/index" => "order#index"
  get "order/show" => "order#show"
  get "order/destroy"
  post "order/order_done"
	get "order/pay" => "order#pay"
	get "order/collection" => "order#collection"
	get "order/pay_success"
	get "order/collection"
	post "order/cancel_collection"
	
	get "cart/show" => "cart#show"
  post "cart/destroy"
	
  get "admin/fruit_type/new" => "admin/fruit_type#new"
  post "admin/fruit_type/create" => "admin/fruit_type#create"
  get "admin/fruit_type/edit"
  post "admin/fruit_type/update"
  post "admin/fruit_type/destroy"
  get "admin/fruit_type/show"
  get "admin/fruit_type" => "admin/fruit_type#index"
	
  get "admin/origin_place/new" => "admin/origin_place#new"
  post "admin/origin_place/create" => "admin/origin_place#create"
  get "admin/origin_place/edit"
  post "admin/origin_place/update"
  post "admin/origin_place/destroy"
  get "admin/origin_place/show"
  get "admin/origin_place" => "admin/origin_place#index"
	
  get "admin/fruit/new" => "admin/fruit#new"
  post "admin/fruit/create" => "admin/fruit#create"
  get "admin/fruit/edit"
  post "admin/fruit/update"
  post "admin/fruit/destroy"
  get "admin/fruit/show"
  get "admin/fruit" => "admin/fruit#index"
	
	get "admin/order/new" => "admin/order#new"
  post "admin/order/create" => "admin/order#create"
  get "admin/order/edit"
  post "admin/order/update"
  post "admin/order/destroy"
  get "admin/order/show"
  get "admin/order/history"
  get "admin/order" => "admin/order#index"
	
	get "admin/login" => "admin/user#login"
	post "admin/login" => "admin/user#login"
	get "admin/logout" => "admin/user#logout"
	get "admin/user/index"
	get "admin/user/information"
	get "admin/user/edit_info"
	post "admin/user/update_info"
	get "admin/user/security"
	get "admin/user/change_password"
	post "admin/user/change_password"
	post "admin/user/update_mail_address"
	get "admin/user/edit_security" 
	post "admin/user/update_security"
	
  get "admin/member/new" => "admin/member#new"
  post "admin/member/create" => "admin/member#create"
  get "admin/member" => "admin/member#index"
  get "admin/member/banned"
  get "admin/member/edit"
  post "admin/member/update"
  post "admin/member/destroy"
  get "admin/member/show"
	
  
  

end

app/views/layouts/_fruit_search.erb
<div style="width:300px; height:400px;" class="fl">
	<div style="padding:25px;">
		<img style="margin:2px audio;" width="250px" height="250px"></img>
	</div>
	<div style=" text-align:center; ">
		<span><%= fruit.id %></span>
		<span><%= fruit.name %></span>
		<span><%= fruit.origin_place.name %></span>
		<span><%= fruit.price_present %></span>
	</div>
</div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @page_title || "FruitHome"%></title>
	<!--% if @page_title %--><!--h1><%= @page_title %></h1--><!--% end %-->
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "pic_list", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "pic_zoom_up", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
		<!-- topbar starts -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%= link_to admin_user_index_path, class:"brand" do %>
					<!-- <img alt="Charisma Logo" src="img/logo20.png" /> -->
					<span>FruitHome</span>
				<% end %>
				
				<!-- theme selector starts -->
				<!-- <div class="btn-group pull-right theme-container" >
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-tint"></i><span class="hidden-phone"> Change Theme / Skin</span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu" id="themes">
						<li><a data-value="classic" href="#"><i class="icon-blank"></i> Classic</a></li>
						<li><a data-value="cerulean" href="#"><i class="icon-blank"></i> Cerulean</a></li>
						<li><a data-value="cyborg" href="#"><i class="icon-blank"></i> Cyborg</a></li>
						<li><a data-value="redy" href="#"><i class="icon-blank"></i> Redy</a></li>
						<li><a data-value="journal" href="#"><i class="icon-blank"></i> Journal</a></li>
						<li><a data-value="simplex" href="#"><i class="icon-blank"></i> Simplex</a></li>
						<li><a data-value="slate" href="#"><i class="icon-blank"></i> Slate</a></li>
						<li><a data-value="spacelab" href="#"><i class="icon-blank"></i> Spacelab</a></li>
						<li><a data-value="united" href="#"><i class="icon-blank"></i> United</a></li>
					</ul>
				</div> -->
				<!-- theme selector ends -->
				
				<!-- user dropdown starts -->
				<div class="btn-group pull-right" >
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-user"></i><span class="hidden-phone"><%= @current_admin_user.username%></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "个人信息", admin_user_information_path %></li>
						<li class="divider"></li>
						<li><%= link_to "退出", admin_logout_path %></li>
					</ul>
				</div>
				<!-- user dropdown ends -->
				
				<div class="top-nav nav-collapse">
					<ul class="nav">
						<li><a href="http://localhost:3000/">浏览商城</a></li>
						<li>
							<!-- <form class="navbar-search pull-left">
								<input placeholder="Search" class="search-query span2" name="query" type="text">
							</form> -->
						</li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<!-- topbar ends -->
	<div class="container-fluid">
		<div class="row-fluid">
			
			<!-- left menu starts -->
			<style type="text/css">
			.nav .nav-header {
				font-size: 20px;
				line-height: 25px;
				color: black;
			}
			</style>	
			<div class="span2 main-menu-span" style="margin:0;">
				<div class="well nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li class="nav-header hidden-tablet">管理员信息</li>
						<li><%= link_to "首页", admin_user_index_path %></li>
						<li><%= link_to "账户信息", admin_user_information_path %></li>
						<li><%= link_to "修改密码", admin_user_change_password_path %></li>
						<li class="nav-header hidden-tablet">会员管理</li>
						<li><%= link_to "查看会员", admin_member_path %></li>
						<li><%= link_to "已屏蔽会员", admin_member_banned_path %></li>
						<li class="nav-header hidden-tablet">商品管理</li>
						<li><%= link_to "查看商品", admin_fruit_path %></li>
						<li><%= link_to "新增商品", admin_fruit_new_path %></li>
						<li><%= link_to "商品类别", admin_fruit_type_path %></li>
						<li><%= link_to "商品产地", admin_origin_place_path %></li>
						<li class="nav-header hidden-tablet">订单管理</li>
						<li><%= link_to "订单处理", admin_order_path %></li>
						<li><%= link_to "历史订单", admin_order_history_path %></li>
						<!-- <li class="nav-header hidden-tablet">留言、评论</li>
						<li><a href="2">新增商品</a></li> -->
					</ul>
					<!-- <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox"> Ajax on menu</label> -->
				</div><!--/.well -->
			</div><!--/span-->
			<!-- left menu ends -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
			<div id="content" class="span10">
			<!-- content starts -->
			
			
			<style type="text/css">
			.nav .nav-header {
				font-size: 20px;
				line-height: 25px;
				color: black;
			}
			</style>	
			<div>
				<ol class="breadcrumb">
					<li>
						<%= link_to "后台管理系统", admin_user_index_path %>
						<!-- <a href="#" class="func_m">后台</a> -->
					</li>
					<li>
						<!-- <a href="#" class="func_i">首页</a> -->
					</li>
				</ol>
			</div>
			
			<!-- <div style="position:relative"> -->
				<%= yield %>
			<!-- </div> -->			
			
			
			<!-- <div class="row-fluid">
				<div class="box span12">
					<div class="box-header well">
						<h2><i class="icon-info-sign"></i> Introduction</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<h1>Charisma <small>free, premium quality, responsive, multiple skin admin template.</small></h1>
						<p>Its a live demo of the template. I have created Charisma to ease the repeat work I have to do on my projects. Now I re-use Charisma as a base for my admin panel work and I am sharing it with you :)</p>
						<p><b>All pages in the menu are functional, take a look at all, please share this with your followers.</b></p>
						
						<p class="center">
							<a href="http://usman.it/free-responsive-admin-template" class="btn btn-large btn-primary"><i class="icon-chevron-left icon-white"></i> Back to article</a> 
							<a href="http://usman.it/free-responsive-admin-template" class="btn btn-large"><i class="icon-download-alt"></i> Download Page</a>
						</p>
						<div class="clearfix"></div>
					</div>
				</div>
			</div> -->
				  
			<!--div style="clear:both"-->

					<!-- content ends -->
			</div><!--/#content.span10-->
		</div><!--/fluid-row-->
				
		<hr>
		
	</div><!--/.fluid-container-->



<% if ENV["RAILS_ENV"] == "development" %>
<div class="alert" style="clear:both; ">
	<%= debug(params) %>
</div>
<% end %>


<script type="text/javascript">
	$(document).onload(function() {     
     $(".func_i")[0].innerText = $("li.active a")[0].innerText;
}); 
	
</script>



<div id="footer">
	<div class="footer_services">
		<strong>各种服务,运输，支付，信息等等</strong>
	</div>
	<div class="footer_links">
		<p>
			<%= link_to "关于FruitHome", about_path %>
			<strong>|</strong>
			<%= link_to "我们的团队", "#" %>
			<strong>|</strong>
			<%= link_to "联系我们", "#" %>
			<strong>|</strong>
			<%= link_to "人才招聘", "#" %>
			<strong>|</strong>
			<%= link_to "友情链接", "#" %>
			<strong>|</strong>
			<%= link_to "广告服务", "#" %>
		</p>
	</div>
	<div class="footer_copyright">
		<p>Copyright© FruitHome 2014-2014， Not All Rights Reserved</p>
		</div>
	<div class="footer_authentication">
		<%= image_tag("authentication.png", style: "cursor:pointer", alt: "尚未取得的授权", title: "尚未取得的授权") %>
	</div>
</div>

<!-- external javascript
================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->


<!-- jQuery -->
<%= javascript_include_tag "jquery-1.7.2.min", "data-turbolinks-track" => true %>

<!-- jQuery UI -->
<%= javascript_include_tag "jquery-ui-1.8.21.custom.min", "data-turbolinks-track" => true %>

<!-- custom dropdown library -->
<%= javascript_include_tag "bootstrap-dropdown", "data-turbolinks-track" => true %>

<!-- library for creating tabs -->
<%= javascript_include_tag "bootstrap-tab", "data-turbolinks-track" => true %>

<!-- library for advanced tooltip -->
<%= javascript_include_tag "bootstrap-tooltip", "data-turbolinks-track" => true %>

<!-- popover effect library -->
<%= javascript_include_tag "bootstrap-popover", "data-turbolinks-track" => true %>

<!-- library for cookie management -->
<%= javascript_include_tag "jquery.cookie", "data-turbolinks-track" => true %>

<!-- calander plugin -->
<!-- <%= javascript_include_tag "fullcalendar.min", "data-turbolinks-track" => true %> -->

<!-- data table plugin -->
<%= javascript_include_tag "jquery.dataTables.min", "data-turbolinks-track" => true %>

<!-- chart libraries start -->
<%= javascript_include_tag "excanvas", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.pie.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.stack", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.resize.min", "data-turbolinks-track" => true %>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<%= javascript_include_tag "jquery.chosen.min", "data-turbolinks-track" => true %>

<!-- checkbox, radio, and file input styler -->
<%= javascript_include_tag "jquery.uniform.min", "data-turbolinks-track" => true %>

<!-- plugin for gallery image view -->
<!-- <%= javascript_include_tag "jquery.colorbox.min", "data-turbolinks-track" => true %> -->

<!-- rich text editor library -->
<%= javascript_include_tag "jquery.cleditor.min", "data-turbolinks-track" => true %>

<!-- notification plugin -->
<!-- <%= javascript_include_tag "jquery.noty", "data-turbolinks-track" => true %> -->

<!-- file manager library -->
<!-- <%= javascript_include_tag "jquery.elfinder.min", "data-turbolinks-track" => true %> -->

<!-- star rating plugin -->
<!-- <%= javascript_include_tag "jquery.raty.min", "data-turbolinks-track" => true %> -->

<!-- for iOS style toggle switch -->
<%= javascript_include_tag "jquery.iphone.toggle", "data-turbolinks-track" => true %>

<!-- autogrowing textarea plugin -->
<%= javascript_include_tag "jquery.autogrow-textarea", "data-turbolinks-track" => true %>

<!-- multiple file upload plugin -->
<!-- <%= javascript_include_tag "jquery.uploadify-3.1.min", "data-turbolinks-track" => true %> -->

<!-- history.js for cross-browser state change on ajax -->
<%= javascript_include_tag "jquery.history", "data-turbolinks-track" => true %>

<!-- application script for Charisma demo -->
<%= javascript_include_tag "charisma", "data-turbolinks-track" => true %>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @page_title || "FruitHome"%></title>
	<!--% if @page_title %--><!--h1><%= @page_title %></h1--><!--% end %-->
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "pic_list", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "pic_zoom_up", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<%= render :partial=> "shared/global_top_bar" %>

<%= render :partial=> "shared/site_header_for_search_and_type" %>



<!--div style="clear:both"-->
<div style="position:relative">
	<%= yield %>
</div>


<% if ENV["RAILS_ENV"] == "development" %>
<div class="alert" style="clear:both; ">
	<%= debug(params) %>
</div>
<% end %>

<div id="footer">
	<div class="footer_services">
		<strong>各种服务,运输，支付，信息等等</strong>
	</div>
	<div class="footer_links">
		<p>
			<%= link_to "关于FruitHome", about_path %>
			<strong>|</strong>
			<%= link_to "我们的团队", "#" %>
			<strong>|</strong>
			<%= link_to "联系我们", "#" %>
			<strong>|</strong>
			<%= link_to "人才招聘", "#" %>
			<strong>|</strong>
			<%= link_to "友情链接", "#" %>
			<strong>|</strong>
			<%= link_to "广告服务", "#" %>
		</p>
	</div>
	<div class="footer_copyright">
		<p>Copyright© FruitHome 2014-2014， Not All Rights Reserved</p>
		</div>
	<div class="footer_authentication">
		<%= image_tag("authentication.png", style: "cursor:pointer", alt: "尚未取得的授权", title: "尚未取得的授权") %>
	</div>
</div>

<!-- external javascript
================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->


<!-- jQuery -->
<%= javascript_include_tag "jquery-1.7.2.min", "data-turbolinks-track" => true %>

<!-- jQuery UI -->
<%= javascript_include_tag "jquery-ui-1.8.21.custom.min", "data-turbolinks-track" => true %>

<!-- custom dropdown library -->
<%= javascript_include_tag "bootstrap-dropdown", "data-turbolinks-track" => true %>

<!-- library for creating tabs -->
<%= javascript_include_tag "bootstrap-tab", "data-turbolinks-track" => true %>

<!-- library for advanced tooltip -->
<%= javascript_include_tag "bootstrap-tooltip", "data-turbolinks-track" => true %>

<!-- popover effect library -->
<%= javascript_include_tag "bootstrap-popover", "data-turbolinks-track" => true %>

<!-- library for cookie management -->
<%= javascript_include_tag "jquery.cookie", "data-turbolinks-track" => true %>

<!-- calander plugin -->
<!-- <%= javascript_include_tag "fullcalendar.min", "data-turbolinks-track" => true %> -->

<!-- data table plugin -->
<!-- <%= javascript_include_tag "jquery.dataTables.min", "data-turbolinks-track" => true %> -->

<!-- chart libraries start -->
<%= javascript_include_tag "excanvas", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.pie.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.stack", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.resize.min", "data-turbolinks-track" => true %>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<%= javascript_include_tag "jquery.chosen.min", "data-turbolinks-track" => true %>

<!-- checkbox, radio, and file input styler -->
<!-- <%= javascript_include_tag "jquery.uniform.min", "data-turbolinks-track" => true %> -->

<!-- plugin for gallery image view -->
<!-- <%= javascript_include_tag "jquery.colorbox.min", "data-turbolinks-track" => true %> -->

<!-- rich text editor library -->
<%= javascript_include_tag "jquery.cleditor.min", "data-turbolinks-track" => true %>

<!-- notification plugin -->
<!-- <%= javascript_include_tag "jquery.noty", "data-turbolinks-track" => true %> -->

<!-- file manager library -->
<!-- <%= javascript_include_tag "jquery.elfinder.min", "data-turbolinks-track" => true %> -->

<!-- star rating plugin -->
<!-- <%= javascript_include_tag "jquery.raty.min", "data-turbolinks-track" => true %> -->

<!-- for iOS style toggle switch -->
<%= javascript_include_tag "jquery.iphone.toggle", "data-turbolinks-track" => true %>

<!-- autogrowing textarea plugin -->
<%= javascript_include_tag "jquery.autogrow-textarea", "data-turbolinks-track" => true %>

<!-- multiple file upload plugin -->
<!-- <%= javascript_include_tag "jquery.uploadify-3.1.min", "data-turbolinks-track" => true %> -->

<!-- history.js for cross-browser state change on ajax -->
<%= javascript_include_tag "jquery.history", "data-turbolinks-track" => true %>

<!-- application script for Charisma demo -->
<%= javascript_include_tag "charisma", "data-turbolinks-track" => true %>


</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @page_title || "FruitHome"%></title>
	<!--% if @page_title %--><!--h1><%= @page_title %></h1--><!--% end %-->
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "pic_list", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "pic_zoom_up", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>


<!--div style="clear:both"-->
<div style="position:relative">
	<%= yield %>
</div>


<% if ENV["RAILS_ENV"] == "development" %>
<div class="alert" style="clear:both; ">
	<%= debug(params) %>
</div>
<% end %>

<div id="footer">
	<div class="footer_services">
		<strong>各种服务,运输，支付，信息等等</strong>
	</div>
	<div class="footer_links">
		<p>
			<%= link_to "关于FruitHome", about_path %>
			<strong>|</strong>
			<%= link_to "我们的团队", "#" %>
			<strong>|</strong>
			<%= link_to "联系我们", "#" %>
			<strong>|</strong>
			<%= link_to "人才招聘", "#" %>
			<strong>|</strong>
			<%= link_to "友情链接", "#" %>
			<strong>|</strong>
			<%= link_to "广告服务", "#" %>
		</p>
	</div>
	<div class="footer_copyright">
		<p>Copyright© FruitHome 2014-2014， Not All Rights Reserved</p>
		</div>
	<div class="footer_authentication">
		<%= image_tag("authentication.png", style: "cursor:pointer", alt: "尚未取得的授权", title: "尚未取得的授权") %>
	</div>
</div>

<!-- external javascript
================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->


<!-- jQuery -->
<%= javascript_include_tag "jquery-1.7.2.min", "data-turbolinks-track" => true %>

<!-- jQuery UI -->
<%= javascript_include_tag "jquery-ui-1.8.21.custom.min", "data-turbolinks-track" => true %>

<!-- custom dropdown library -->
<%= javascript_include_tag "bootstrap-dropdown", "data-turbolinks-track" => true %>

<!-- library for creating tabs -->
<%= javascript_include_tag "bootstrap-tab", "data-turbolinks-track" => true %>

<!-- library for advanced tooltip -->
<%= javascript_include_tag "bootstrap-tooltip", "data-turbolinks-track" => true %>

<!-- popover effect library -->
<%= javascript_include_tag "bootstrap-popover", "data-turbolinks-track" => true %>

<!-- library for cookie management -->
<%= javascript_include_tag "jquery.cookie", "data-turbolinks-track" => true %>

<!-- calander plugin -->
<!-- <%= javascript_include_tag "fullcalendar.min", "data-turbolinks-track" => true %> -->

<!-- data table plugin -->
<!-- <%= javascript_include_tag "jquery.dataTables.min", "data-turbolinks-track" => true %> -->

<!-- chart libraries start -->
<%= javascript_include_tag "excanvas", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.pie.min", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.stack", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.flot.resize.min", "data-turbolinks-track" => true %>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<%= javascript_include_tag "jquery.chosen.min", "data-turbolinks-track" => true %>

<!-- checkbox, radio, and file input styler -->
<!-- <%= javascript_include_tag "jquery.uniform.min", "data-turbolinks-track" => true %> -->

<!-- plugin for gallery image view -->
<!-- <%= javascript_include_tag "jquery.colorbox.min", "data-turbolinks-track" => true %> -->

<!-- rich text editor library -->
<%= javascript_include_tag "jquery.cleditor.min", "data-turbolinks-track" => true %>

<!-- notification plugin -->
<!-- <%= javascript_include_tag "jquery.noty", "data-turbolinks-track" => true %> -->

<!-- file manager library -->
<!-- <%= javascript_include_tag "jquery.elfinder.min", "data-turbolinks-track" => true %> -->

<!-- star rating plugin -->
<!-- <%= javascript_include_tag "jquery.raty.min", "data-turbolinks-track" => true %> -->

<!-- for iOS style toggle switch -->
<%= javascript_include_tag "jquery.iphone.toggle", "data-turbolinks-track" => true %>

<!-- autogrowing textarea plugin -->
<%= javascript_include_tag "jquery.autogrow-textarea", "data-turbolinks-track" => true %>

<!-- multiple file upload plugin -->
<!-- <%= javascript_include_tag "jquery.uploadify-3.1.min", "data-turbolinks-track" => true %> -->

<!-- history.js for cross-browser state change on ajax -->
<%= javascript_include_tag "jquery.history", "data-turbolinks-track" => true %>

<!-- application script for Charisma demo -->
<%= javascript_include_tag "charisma", "data-turbolinks-track" => true %>


</body>
</html>